version: '3.7'

services:
  composer:
    image: 'composer:1.8'
    command: install
    volumes:
      - './:/app'
      -
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - "8085:80"
    depends_on:
    - mariadb

  phpapp:
    build: .
    ports:
      - "8081:80"
    depends_on:
    - mariadb
    volumes:
      - .:/var/www/html